name: 'testkube'
description: 'Runs testkube'
inputs:
  test-suite-name:
    description: "The name of the test suite to run"
    required: true
    default: "infra-base"
  enable-debug:
    description: "Enable debug output during the action run"
    required: false
    default: "false"
  cluster-name:
    description: "Cluster name of test suite is hosted"
    required: true
    default: "env-name"
  testkube-version:
    description: "Specific version of https://github.com/kubeshop/testkube/releases"
    required: true
    default: "v0.11.5"

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test-suite-name }}
    - ${{ inputs.enable-debug }}
    - ${{ inputs.cluster-name }}
    - ${{ inputs.testkube-version }}
