name: 'testkube'
description: 'Runs testkube'
inputs:
  test-suite-name:
    description: "The name of the test suite to run"
    required: true
    default: "infra-base"
  
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test-suite-name }}
